# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
  	config.vm.network "forwarded_port", guest: 4000, host: 4000
	config.vm.network "forwarded_port", guest: 3001, host: 3001
    config.vm.hostname = "scotchbox"
	config.vm.synced_folder "../data", "/var/www/public", :mount_options => ["dmode=777", "fmode=666"], create: true
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end
